services: 
  mysql: 
    image: mysql:latest
    restart: always
    container_name: db_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: db_user
      MYSQL_PASSWORD: dbpass
    ports:
    - "3306:3306"
    volumes: 
    - mysql_data:/var/lib/mysql

  grafana: 
    image: grafana/grafana:latest
    container_name: argus_grafana
    ports:
      - "3000:3000"
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes: 
      - grafana_data:/var/lib/grafana
    depends_on: 
      - mysql
volumes:
  mysql_data:
  grafana_data: