services: 
  mysql: 
    image: mysql:latest
    restart: always
    container_name: db_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: db_user
      MYSQL_PASSWORD: dbpass
    ports:
    - "3306:3306"
    volumes: 
    - mysql_data:/var/lib/mysql

volumes:
  mysql_data: